### ISSUE TITLE
Calendar gives 404

### ISSUE THREAD

**Issue by ICanNomNoms** [SCCapstone/CapstoneProject#106]
The user should not have to do anything for the calendar to work properly.
<img width="1357" alt="done" src="https://user-images.githubusercontent.com/44646798/162579691-75179233-27d3-4d39-8c6d-6525237a0aec.PNG">

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/ed45075859911cfd8cb547636d57d62ff4c72f21
