### ISSUE TITLE
Remove or add rows should be one at a time or select how many to add

### ISSUE THREAD

**Issue by ICanNomNoms** [SCCapstone/CapstoneProject#107]
Otherwise you end up deleting data that needs to be kept.

https://user-images.githubusercontent.com/44646798/162579836-a79ae0d0-0a54-4c5f-b04b-624b313ba8c0.mov

**Comment by ICanNomNoms** [comment]
Same with chores

https://user-images.githubusercontent.com/44646798/162579882-9a7a0a96-4379-4364-8bd0-0b774f1a8f9e.mov

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/d502b91568feabea6c2672206f996b71abb1b27a
