### ISSUE TITLE
Extra white box in drop down menu

### ISSUE THREAD

**Issue by ICanNomNoms** [SCCapstone/CapstoneProject#109]
https://user-images.githubusercontent.com/44646798/162579990-181e30c8-7508-4fff-9b18-ffa7efd0814f.mov

**Comment by Nicolas-A-Becker** [comment]
So I intentionally left the blank box in as the default case in these pages. If the user wants to add rows they select "Add Rows", if they want to delete rows they select "Delete Rows", and if they don't select either then no rows will be created or destroyed. Many pages I use utilize blank space as a default no-input filler for boxes like these. Is there a particular different way that I should allow the user to not select to add or delete rows? This is what I felt made sense at the time but if it doesn't come across clearly then I'm completely open to suggestions on how to make it more clear.

**Comment by Nicolas-A-Becker** [comment]
White box is to allow the box to remain empty when not adding or deleting rows. This will remain for functionality.
