### ISSUE TITLE
Display warning message or do not allow updates with invalid settings data

### ISSUE THREAD

**Issue by kelli-alan** [SCCapstone/CapstoneProject#113]
Invalid room assignments are automatically set to 0 without explanation. A message such as "room numbers must be 4 digits" would be helpful for the user

https://user-images.githubusercontent.com/70072926/162624670-9e43f717-6db4-43b8-bd06-8aeb14bf4283.mp4

**Comment by Nicolas-A-Becker** [comment]
0 is not an invalid room number, however, any non-integer is an invalid number. Zero is the default if room number entered is not of correct data type. This is merely data validation so will remain.
