### ISSUE TITLE
Logout button displays when user is not logged in

### ISSUE THREAD

**Issue by kelli-alan** [SCCapstone/CapstoneProject#114]
Log Out button is not necessary when a user is not signed in

![Sign In - Google Chrome 2022-04-10 09 47 22](https://user-images.githubusercontent.com/70072926/162624958-d3876106-964c-4468-b50f-531af1a4fe37.png)

**Comment by Nicolas-A-Becker** [comment]
This is merely checking if user is logged in. The button does not hurt being there while the user is logged in so it will remain visible or be removed entirely.
