### ISSUE TITLE
Hide blank data on home page

### ISSUE THREAD

**Issue by kelli-alan** [SCCapstone/CapstoneProject#115]
Some cosmetic suggestions:
Instead of a blank house number, indicate it is unknown
Instead of blank alerts, show a message such as "no alerts" or do not display that section
Instead of blank chores, add an "add chores" button that goes to the chores page

![Housemates - Google Chrome 2022-04-10 10 47 39](https://user-images.githubusercontent.com/70072926/162625298-d3ec1f53-e06c-4d42-bf03-3eda5171b56f.png)

**Comment by Nicolas-A-Becker** [comment]
This issue is just a cosmetic enhancement and allows the user to see possibilities even when empty
