### ISSUE TITLE
Calendar display blank/not syncing with google calendar

### ISSUE THREAD

**Issue by pattersonhowell** [SCCapstone/CapstoneProject#116]
I followed the steps to remove the 404 error which worked. However, now the page is blank. I updated my google calendar with events, but nothing ever appeared on Housemates even after reloading and signing in again.
<img width="1436" alt="Screen Shot 2022-04-10 at 2 50 54 PM" src="https://user-images.githubusercontent.com/70411201/162635326-9b1c6a17-eca8-406d-9d65-381e1914389d.png">

**Comment by Nicolas-A-Becker** [comment]
must make calendar public
