### ISSUE TITLE
Inputting info in Settings leads to error page

### ISSUE THREAD

**Issue by pattersonhowell** [SCCapstone/CapstoneProject#117]
When inputting housing information (using dummy data) and then pressing publish button, the page redirects to an error screen. If my information being inputted is not acceptable, maybe there should be a warning to fix it and not show an error page. Also, the information does not get displayed in the Contact field afterward.

https://user-images.githubusercontent.com/70411201/162635504-6d5c92c0-07e5-47e2-b1f0-8f00c0f4006c.mov

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/f6a6e837fdaf1649b8c0c018a1c8f816c2b835ee
