### ISSUE TITLE
Inputting Emergency Contact Info leads to error page

### ISSUE THREAD

**Issue by pattersonhowell** [SCCapstone/CapstoneProject#118]
When inputting emergency contact information (using dummy data), the page redirects to an error page. If my formatting is incorrect, maybe the user should be warned and not be allowed to click the publish button until it is fixed.

https://user-images.githubusercontent.com/70411201/162635656-e9a78b72-b92a-4372-adcf-2588904f0329.mov

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/f6a6e837fdaf1649b8c0c018a1c8f816c2b835ee
