### ISSUE TITLE
Chores Submit Button is confused

### ISSUE THREAD

**Issue by pattersonhowell** [SCCapstone/CapstoneProject#120]
When adding a list of chores, then pressing submit to update the list, a chunk of chores is deleted leaving just the first item. NOTE: the feature worked fine the first time I used it, but after experimenting around with other buttons/features this is happening now.

https://user-images.githubusercontent.com/70411201/162636271-6a3badb0-251c-42f2-819a-45f97f8c26b9.mov

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/bb3db60a25c31cc8cec5df8636070d179b62a963
