### ISSUE TITLE
Shopping Submit Button is confused

### ISSUE THREAD

**Issue by pattersonhowell** [SCCapstone/CapstoneProject#121]
When adding a list of groceries, then pressing submit to update the list, a chunk of groceries is deleted leaving just the first item. NOTE: the feature worked fine the first time I used it, but after experimenting around with other buttons/features this is happening now.

https://user-images.githubusercontent.com/70411201/162636362-87937658-07f1-43c3-b009-81f2783c029a.mov

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/bb3db60a25c31cc8cec5df8636070d179b62a963
