### ISSUE TITLE
Click contact resulting an error

### ISSUE THREAD

**Issue by zhiquan114514** [SCCapstone/CapstoneProject#123]
![KQJTN`YZYDKI6Q47SIW7~EU](https://user-images.githubusercontent.com/69903223/162645560-45f144d6-8310-4c3e-978b-998681f7c8f6.png)

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/fafe2796b98ab6911d141357d10bdd01d71b957a
