### ISSUE TITLE
Routing from Calendar Page to personalSettings not working

### ISSUE THREAD

**Issue by desmartw** [SCCapstone/CapstoneProject#124]
When I try to go from the calendar page to the Personal Settings Page from the link in Calendar integration instructions, the following error occurs.

https://user-images.githubusercontent.com/55217897/163454562-271a36ea-9c86-48a0-884a-50a5fc9e8719.mov

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/f6a6e837fdaf1649b8c0c018a1c8f816c2b835ee
