### ISSUE TITLE
Unclear what Alerts are and how to add or edit them

### ISSUE THREAD

**Issue by desmartw** [SCCapstone/CapstoneProject#125]
From the homepage, with a new account I am not sure what the "Alerts:" information presented on the Home Screen means, and I could not find how to update it.

![Screen Shot 2022-04-14 at 2 42 44 PM](https://user-images.githubusercontent.com/55217897/163456024-d743d997-9a3d-4d26-bf57-5f6ba672036a.png)

**Comment by Nicolas-A-Becker** [comment]
Alerts are not to be edited from the home page. An explanation or different formatting may be added to make this more clear if available time allows it, but not a major bug.
