### ISSUE TITLE
Provide Options for Urgency

### ISSUE THREAD

**Issue by desmartw** [SCCapstone/CapstoneProject#126]
I think it would be more clear if I could choose from a list of options for the urgency column. For example ['not important', 'do today', 'extremely urgent',...] or something similar. This would also prevent users from accidentally putting shopping items in the Urgency column by tabbing over.

![Screen Shot 2022-04-14 at 2 47 33 PM](https://user-images.githubusercontent.com/55217897/163456734-f8a77005-0473-4a64-bf4d-53439f0e356b.png)

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/e80f8bc5b2361e5bd1e63c4460d46a74d112919f
