### ISSUE TITLE
Would like a way to clear the whole list, Chores or Shopping

### ISSUE THREAD

**Issue by desmartw** [SCCapstone/CapstoneProject#127]
By deleting rows when already at the minimum number of rows, this deletes everything except the first row, however it resets the assignment of the first row. I think if there was a 'Clear All' button on both list pages it would be a helpful feature.

https://user-images.githubusercontent.com/55217897/163458686-ff05cd45-3c5d-4b38-b9d2-b8e47132abd7.mov

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/bb3db60a25c31cc8cec5df8636070d179b62a963
