### ISSUE TITLE
 When publishing housing info page, throws an Route [pages.settingsPages.informationSettings] not defined error.

### ISSUE THREAD

**Issue by BranavanKalapathy23** [SCCapstone/CapstoneProject#129]
https://user-images.githubusercontent.com/54036018/163730214-1dfcd867-3303-450d-87c4-68be2917dbd6.mp4

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/f6a6e837fdaf1649b8c0c018a1c8f816c2b835ee
