### ISSUE TITLE
Suggestion for shopping page, rename the field 'done?' to 'status'.

### ISSUE THREAD

**Issue by BranavanKalapathy23** [SCCapstone/CapstoneProject#130]
https://user-images.githubusercontent.com/54036018/163730346-837a60ea-18d1-447b-9e1a-dac584111053.mp4

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/ed45075859911cfd8cb547636d57d62ff4c72f21
