### ISSUE TITLE
Deploy webapp to Forge.

### ISSUE THREAD

**Issue by OMHavec** [SCCapstone/CapstoneProject#22]

**Comment by josemvidal** [comment]
This feature appears to be implemented. Why is this still open?

After you do and Issue, you close it, with a comment that points to the commit that closes it. In GitHub you can [do this automatically](https://help.github.com/articles/closing-issues-using-keywords/) by just writing "closes #xx" in the git-commit comment.

Please watch my [teamwork lecture](https://cse.sc.edu/capstone/lecture/teamwork) which explains all this an more.
