### ISSUE TITLE
Redeployment

### ISSUE THREAD

**Issue by ctreid** [SCCapstone/CapstoneProject#56]
@josemvidal We are taking down the server to help troubleshoot and successfully redeploy with the database linked correctly. We will close this issue once it has been redeployed.

**Comment by josemvidal** [comment]
No need. The deadline was last Friday. We grade that. See https://capstone.cse.sc.edu/490syllabus/#late-workmake-up-policy

**Comment by Nicolas-A-Becker** [comment]
http://159.223.154.171
