### ISSUE TITLE
Functional logins using Google OAuth

### ISSUE THREAD

**Issue by OMHavec** [SCCapstone/CapstoneProject#65]

**Comment by laurenelee99** [comment]
Having trouble implementing and connecting Google OAuth. @josemvidal do you have experience with this?

**Comment by josemvidal** [comment]
Nope, I have not done that.

I found this: [🔐 🌈 Add Login with Google to your Laravel app | by Connor Leech | Employbl | Medium](https://medium.com/employbl/add-login-with-google-to-your-laravel-app-d2205f01b895)

**Comment by laurenelee99** [comment]
Thanks! I followed that one and a few others.. Thinking it must have something to do with the credentials

**Comment by laurenelee99** [comment]
Got the Google OAuth running and populating the database.

**Comment by ctreid** [comment]
Login is functional if you use Safari or Opera, but Chrome is currently not working.
