### ISSUE TITLE
Calendar is 404

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CapstoneProject#84]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/228704/156086872-347e0dbc-f171-4b00-bac7-2caf29b3c2b6.png">

**Comment by josemvidal** [comment]
Yes, don't tell the user "404", instead tell the user "click here to add.....".

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/86120834219f2845404caa8442d06e38b7d67c90
