### ISSUE TITLE
Cannot assign roommates to house

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CapstoneProject#85]
#70 says I should be able to, but I don't see how:

https://user-images.githubusercontent.com/228704/156087151-3abc112a-8009-48c0-bd20-d77945070590.mp4

**Comment by josemvidal** [comment]
So, I cannot share my Chores or Shopping list with my roommates, because I don't have any.

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/40d4a5888af6ae0b368366eb59ec42a3e7ed6687
