### ISSUE TITLE
Crashes when new user clicks on  /contact

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CapstoneProject#86]
https://user-images.githubusercontent.com/228704/156087533-acdad823-c770-4e3b-b28f-4aa30bab0703.mp4

**Comment by Nicolas-A-Becker** [comment]
Working to fix this issue now. 
I've not yet been able to replicate this issue in the current release. I had fixed this issue before so I believe it is an initialization error. With that in mind I believe it's related to a sign-in error we've been having. Should be a simple fix to confirm initialization before loading the page.

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/9ec278172ce75214bc40649a3cf0a2fad20a1074
